linters-settings:
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/maiko/sdbx
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    # - goconst  # TODO: Fix string literals to use existing constants
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - gochecknoinits  # Standard pattern for Cobra CLI commands
    - gocognit
    - godox
    - wsl

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - .github
    - docs

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - lll

    # Exclude known false positives
    - path: cmd/sdbx/cmd/
      text: "G204: Subprocess launched with variable"
      linters:
        - gosec

    # Integrate package has similar API clients with naturally similar patterns
    - path: internal/integrate/
      linters:
        - dupl

    # Web handlers have similar request/response patterns
    # errcheck excluded: HTTP response writes rarely need error handling
    - path: internal/web/handlers/
      linters:
        - dupl
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
