linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow         # Variable shadowing is common in Go error handling
      - fieldalignment # Struct field reordering is a micro-optimization
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  goconst:
    min-len: 5
    min-occurrences: 5
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/maiko/sdbx
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    # - goconst  # TODO: Fix string literals to use existing constants
    # - gocritic  # TODO: Fix style issues (ifElseChain, hugeParam, etc.)
    - gocyclo
    - gofmt
    - goimports
    # - revive  # TODO: Fix unused parameters and naming conventions
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    # - prealloc  # TODO: Fix slice preallocation (low priority optimization)
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - gochecknoglobals
    - gochecknoinits  # Standard pattern for Cobra CLI commands
    - gocognit
    - godox
    - wsl

run:
  timeout: 5m
  tests: true

issues:
  exclude-dirs:
    - vendor
    - .github
    - docs

  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - govet
        - lll
        - revive

    # Registry package has ctx parameters for interface compliance
    - path: internal/registry/
      linters:
        - revive

    # Exclude known false positives
    - path: cmd/sdbx/cmd/
      text: "G204: Subprocess launched with variable"
      linters:
        - gosec

    # CLI commands have style patterns that gocritic flags
    - path: cmd/sdbx/cmd/
      linters:
        - gocritic

    # G306: Config files need 0644 for Docker/other services to read them
    - text: "G306:"
      linters:
        - gosec

    # Backup code operates on trusted internal data
    - path: internal/backup/
      linters:
        - gosec
        - revive
        - gocritic

    # Integrate package has similar API clients with naturally similar patterns
    - path: internal/integrate/
      linters:
        - dupl

    # Web handlers have similar request/response patterns
    # errcheck excluded: HTTP response writes rarely need error handling
    - path: internal/web/handlers/
      linters:
        - dupl
        - errcheck

    # Web middleware and tests have common patterns
    - path: internal/web/middleware/
      linters:
        - revive

    # Doctor package has standard check patterns
    - path: internal/doctor/
      linters:
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
